version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  ### CORE RPC SERVICE #########################################
  core-rpc:
    image: kebin6/core-rpc:${CORE_VERSION}
    container_name: core-rpc
    restart: always
    ports:
      - '9101:9101'
    volumes:
      - ${LOG_DATA_DIR}/core/rpc:/home/data/logs
      - ${CONFIG_DATA_DIR}/core/rpc:/app/etc
    networks:
      backend:
        aliases:
          - core-rpc

  ### CORE API SERVICE #########################################
  core-api:
    image: kebin6/core-api:${CORE_VERSION}
    container_name: core-api
    restart: always
    environment:
      I18N_DIR: '/app'
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - '9100:9100'
    volumes:
      - ${LOG_DATA_DIR}/core/api:/home/data/logs
      - ${CONFIG_DATA_DIR}/core/api:/app/etc
      - ${CONFIG_DATA_DIR}/locale:/app/locale
    networks:
      backend:
        aliases:
          - core-api

  ### FILE API SERVICE #########################################
  file-api:
    image: kebin6/fms-api:${FILE_VERSION}
    container_name: file-api
    restart: always
    environment:
      I18N_DIR: '/app'
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - '9102:9102'
    volumes:
      - ${LOG_DATA_DIR}/file/api:/home/data/logs
      - ${CONFIG_DATA_DIR}/file/api:/app/etc
      - ${CONFIG_DATA_DIR}/locale:/app/locale
    networks:
      backend:
        aliases:
          - file-api

  ### MESSAGE RPC SERVICE #########################################
  message-rpc:
    image: kebin6/mcms-rpc:${MESSAGE_VERSION}
    container_name: message-rpc
    restart: always
    ports:
      - '9106:9106'
    volumes:
      - ${LOG_DATA_DIR}/message/rpc:/home/data/logs
      - ${CONFIG_DATA_DIR}/message/rpc:/app/etc
    networks:
      backend:
        aliases:
          - message-rpc

  ### SOLAMB RPC SERVICE #########################################
  solamb-rpc:
    image: kebin6/wolflamp-rpc:${SOLAMB_RPC_VERSION}
    container_name: solamb-rpc
    restart: always
    ports:
      - '7002:7002'
    volumes:
      - ${LOG_DATA_DIR}/solamb/rpc:/home/data/logs
      - ${CONFIG_DATA_DIR}/solamb/rpc:/app/etc
    networks:
      backend:
        aliases:
          - solamb-rpc

  ### SOLAMB API SERVICE #########################################
  solamb-api:
    image: kebin6/wolflamp-api:${SOLAMB_API_VERSION}
    container_name: solamb-api
    restart: always
    environment:
      I18N_DIR: '/app'
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - '8002:8002'
    volumes:
      - ${LOG_DATA_DIR}/solamb/api:/home/data/logs
      - ${CONFIG_DATA_DIR}/solamb/api:/app/etc
      - ${CONFIG_DATA_DIR}/locale:/app/locale
    networks:
      backend:
        aliases:
          - solamb-api

  ### APP API SERVICE #########################################
  app-api:
    image: kebin6/app-api:${SOLAMB_APP_VERSION}
    container_name: app-api
    restart: always
    environment:
      I18N_DIR: '/app'
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - '8080:8080'
    volumes:
      - ${LOG_DATA_DIR}/app/api:/home/data/logs
      - ${CONFIG_DATA_DIR}/app/api:/app/etc
      - ${CONFIG_DATA_DIR}/locale:/app/locale
    networks:
      backend:
        aliases:
          - app-api

  ### JOB RPC SERVICE #########################################
  job-rpc:
    image: kebin6/job-rpc:${JOB_RPC_VERSION}
    container_name: job-rpc
    restart: always
    ports:
      - '9105:9105'
    volumes:
      - ${LOG_DATA_DIR}/job/rpc:/home/data/logs
      - ${CONFIG_DATA_DIR}/job/rpc:/app/etc
    networks:
      backend:
        aliases:
          - job-rpc
